//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAssistant.DataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.AzureAppService")]
    public interface AzureAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/AddApp", ReplyAction="http://tempuri.org/AzureAppService/AddAppResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TokenAssistant.Data.ClientAzureApp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TokenAssistant.Data.ServerAzureApp))]
        void AddApp(TokenAssistant.Data.AzureApp app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/AddApp", ReplyAction="http://tempuri.org/AzureAppService/AddAppResponse")]
        System.Threading.Tasks.Task AddAppAsync(TokenAssistant.Data.AzureApp app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/DeleteApp", ReplyAction="http://tempuri.org/AzureAppService/DeleteAppResponse")]
        void DeleteApp(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/DeleteApp", ReplyAction="http://tempuri.org/AzureAppService/DeleteAppResponse")]
        System.Threading.Tasks.Task DeleteAppAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/GetAllApps", ReplyAction="http://tempuri.org/AzureAppService/GetAllAppsResponse")]
        TokenAssistant.Data.AzureApp[] GetAllApps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/GetAllApps", ReplyAction="http://tempuri.org/AzureAppService/GetAllAppsResponse")]
        System.Threading.Tasks.Task<TokenAssistant.Data.AzureApp[]> GetAllAppsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/GetApp", ReplyAction="http://tempuri.org/AzureAppService/GetAppResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TokenAssistant.Data.ClientAzureApp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TokenAssistant.Data.ServerAzureApp))]
        TokenAssistant.Data.AzureApp GetApp(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/GetApp", ReplyAction="http://tempuri.org/AzureAppService/GetAppResponse")]
        System.Threading.Tasks.Task<TokenAssistant.Data.AzureApp> GetAppAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/SaveApp", ReplyAction="http://tempuri.org/AzureAppService/SaveAppResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TokenAssistant.Data.ClientAzureApp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TokenAssistant.Data.ServerAzureApp))]
        void SaveApp(TokenAssistant.Data.AzureApp app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/SaveApp", ReplyAction="http://tempuri.org/AzureAppService/SaveAppResponse")]
        System.Threading.Tasks.Task SaveAppAsync(TokenAssistant.Data.AzureApp app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/SaveChanges", ReplyAction="http://tempuri.org/AzureAppService/SaveChangesResponse")]
        void SaveChanges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AzureAppService/SaveChanges", ReplyAction="http://tempuri.org/AzureAppService/SaveChangesResponse")]
        System.Threading.Tasks.Task SaveChangesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AzureAppServiceChannel : TokenAssistant.DataService.AzureAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AzureAppServiceClient : System.ServiceModel.ClientBase<TokenAssistant.DataService.AzureAppService>, TokenAssistant.DataService.AzureAppService {
        
        public AzureAppServiceClient() {
        }
        
        public AzureAppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AzureAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AzureAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AzureAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddApp(TokenAssistant.Data.AzureApp app) {
            base.Channel.AddApp(app);
        }
        
        public System.Threading.Tasks.Task AddAppAsync(TokenAssistant.Data.AzureApp app) {
            return base.Channel.AddAppAsync(app);
        }
        
        public void DeleteApp(string clientId) {
            base.Channel.DeleteApp(clientId);
        }
        
        public System.Threading.Tasks.Task DeleteAppAsync(string clientId) {
            return base.Channel.DeleteAppAsync(clientId);
        }
        
        public TokenAssistant.Data.AzureApp[] GetAllApps() {
            return base.Channel.GetAllApps();
        }
        
        public System.Threading.Tasks.Task<TokenAssistant.Data.AzureApp[]> GetAllAppsAsync() {
            return base.Channel.GetAllAppsAsync();
        }
        
        public TokenAssistant.Data.AzureApp GetApp(string clientId) {
            return base.Channel.GetApp(clientId);
        }
        
        public System.Threading.Tasks.Task<TokenAssistant.Data.AzureApp> GetAppAsync(string clientId) {
            return base.Channel.GetAppAsync(clientId);
        }
        
        public void SaveApp(TokenAssistant.Data.AzureApp app) {
            base.Channel.SaveApp(app);
        }
        
        public System.Threading.Tasks.Task SaveAppAsync(TokenAssistant.Data.AzureApp app) {
            return base.Channel.SaveAppAsync(app);
        }
        
        public void SaveChanges() {
            base.Channel.SaveChanges();
        }
        
        public System.Threading.Tasks.Task SaveChangesAsync() {
            return base.Channel.SaveChangesAsync();
        }
    }
}
